# Generated by Django 4.2.10 on 2024-02-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=233, null=True)),
                ('fname', models.CharField(max_length=233, null=True)),
                ('lname', models.CharField(max_length=233, null=True)),
                ('age', models.DateTimeField(null=True)),
                ('gender', models.CharField(max_length=233, null=True)),
                ('image', models.TextField(null=True)),
                ('role', models.CharField(max_length=233, null=True)),
            ],
        ),
    ]
