# Generated by Django 4.2.10 on 2024-03-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streem', models.CharField(max_length=223, null=True)),
                ('descr', models.TextField(null=True)),
                ('nsub', models.IntegerField(null=True)),
            ],
        ),
    ]
