# Generated by Django 4.2.10 on 2024-03-02 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_streem_grade_streem_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(null=True)),
                ('section', models.CharField(max_length=20, null=True)),
                ('nas', models.IntegerField(null=True)),
                ('teach', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='streem',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.section'),
        ),
    ]
