# Generated by Django 4.2.10 on 2024-03-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_section_streem_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='grade',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
