# Generated by Django 4.2.10 on 2024-03-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_alter_section_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='grad',
            field=models.IntegerField(null=True),
        ),
    ]
