# Generated by Django 4.2.10 on 2024-03-02 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_section_grad'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.section'),
        ),
    ]
